### ISSUE TITLE
Demo web site : create framework to demo the prototype

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#105]
Josh has made quite a bit of progress on the web app and talking with him, it would be interesting to show a demo of the app on the presentation web page for the January 1rst deadline. I suggest the following:

- [x] Add a Demo button that can launch a controlled version of the app. Add a text like "Click on the Demo button to see our progress".

- [ ] Have a progress update page where we can document release updates as we update the online demo.

- [x]  Create a demo subdomain to allow to have a stable controlled demo version. We will need to define how often we want to update that demo version. Monthly? Every 6 weeks? Every time we make a noticeable change?...

- [ ] Create release versions : 0.0.1 for the first demo? 

- [ ] Add some blurb about work in progress and the need to have early adopters worldwide to help populate our database and provide feedback by using the contact form.

Any other ideas, to make sure we showcase the app progress?

**Comment by stephanosm** [comment]
Yes, good idea!

**Comment by joshi1983** [comment]
Maybe someone can put together a video to highlight what we want to show out of the current work on the site.  I mean something like https://www.youtube.com/watch?v=cpaqPxNhT_o but for accesslocator.

How does this relate to #97 ?  How frequently would this demo site get improvements compared to the test site?  For the test site, I assume I can delete all data and recreate it when updating but will that be the case for this demo site?  It can be about 30% - 50% faster to develop with the freedom to recreate all data so I'd like to hold that freedom until we're almost beta testing.

We can start doing this any time but I'd like to know down to a specific day when this should start because there will be significant overhead associated with this after it starts.  Writing release notes for every change, maintaining multiple deployments, potential data migrations instead of completely replaced take time above and beyond the core development of a change/fix.  Is January 1 a good day for this demo site to start and every change following to come with release notes?

**Comment by joshi1983** [comment]
[demo.accesslocator.com](http://demo.accesslocator.com) is available.  It'll be updated every time app.accesslocator.com is updated for now.  Maybe that'll change after January 1.

**Comment by stephanosm** [comment]
the map doesn't show on the demo

**Comment by joshi1983** [comment]
Good find @stephanosm .  I'll fix.

**Comment by joshi1983** [comment]
@stephanosm it should work now.  The same problem hit test.accesslocator.com and it was fixed too.

**Comment by Blandine-AA** [comment]
Demo and Test subdomaines created. This can be closed now!
