### ISSUE TITLE
Search result page : Sketch and functionality

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#135]
When searching by categories, a list of locations found  within the specified distance is displayed. Two views are available: Map and Table. 
2 tasks in this issue:

- [x] sketch out the page. 
- [x] implement the functionality

Below is the hand sketch of what it is expected. 
![locations found](https://cloud.githubusercontent.com/assets/20052162/21443744/5bc49ede-c875-11e6-8cf6-6a4adc5b8270.jpg)

**Comment by joshi1983** [comment]
I added the Accessibility Rating column, distance, and the table/map links but there's a lot of work left on this issue.

**Comment by joshi1983** [comment]
Would anyone want to sort in descending order?  I know that would be a popular option in applications like Excel or Access but I wonder if that could be simplified down to only ascending for our application.  Sorting to see most distant locations first or lowest rating first seems funny.  Descending sort by name still seems equally reasonable to ascending, though.

A sorted column should be pretty obvious from looking at the data but should we also mark the sorted column in a special colour or icon to make it even more clear?

**Comment by stephanosm** [comment]
I believe the more visualization the better it is. I don't think we need
descending. I suggest we have the sorting by closer distance, by rating and
by ascending(all).

**Comment by joshi1983** [comment]
I added a subtle vertical arrow pattern behind the sorted column based on feedback from @stephanosm .

This screenshot shows the spreadsheet sorted by distance.
![image](https://cloud.githubusercontent.com/assets/11838191/22678162/0a019028-ecc6-11e6-980a-71d0460d72ae.png)

**Comment by Blandine-AA** [comment]
@baseer110, please test this feature using [demo.accesslocator.com ](demo.accesslocator.com). Thanks!

**Comment by baseer110** [comment]
Hello Josh, I have checked the functionality on http://demo.accesslocator.com/ for search result. As per the above image for sorted distance, actually when I have searched for Education category the distance are not sorted and as per the comment by Dr.Stephanos the distance should be near by search location but I am didn't see the sorted distance.

![image](https://cloud.githubusercontent.com/assets/4041079/24054499/d97e9804-0b12-11e7-8dc8-616c5c691509.png)


For example I have used the University of Windsor for search location: 

![image](https://cloud.githubusercontent.com/assets/4041079/24054407/740c8c88-0b12-11e7-9c82-f6432abe1da1.png)

And the result is: 

![image](https://cloud.githubusercontent.com/assets/4041079/24054429/87d2cdd6-0b12-11e7-9d02-c3797ebda6c2.png)

**Comment by Blandine-AA** [comment]
@baseer110 , sorting is done either per location name or per rating value or per distance. 

@joshi1983 , is sorting on the distance implemented or just sorting per location name?

**Comment by joshi1983** [comment]
Sorting by any column is implemented.  You just have to click the column title and it'll work.

In the meeting, Areeba and Baseer relayed that Stephanos wanted it sorted by distance by default.  By "default", I mean immediately when you visit the page after searching on the home page.  It is sorted by name by default, though.  @Blandine-AA, do you also want it sorted by distance by default?

**Comment by stephanosm** [comment]
When I mentioned about sorting by distance by default I had something else in mind. Suppose you search for "restaurant" because you want something around you. That makes sense to be sorted by distance. However, in order for this to work, locations must belong to a type, e.g. Burger King belongs to Restaurant. This has some kind of complexity for assigning locations to types/categories and we might not need to implement it. 
The way it is currently developed is correct since name is more important that location. What I would recommend thought is to highlight (change color) the column title that is sorted, by default is NAME and perhaps underline the other 2 columns indicating that those are links as well.  As it is right now, users might not understand that these are actually links that can sort the columns.

**Comment by joshi1983** [comment]
@stephanosm using the underlining and colour to bring attention to the sorting feature sounds like a good idea.  

A few people verified with me that there was a sorting feature last night when I expected it to be obvious from the website.  I overestimated how noticable the feature was so I added the underlining and colour changes you suggested.  You can review the changes at http://app.accesslocator.com/location-search?keywords=&order_by=distance&location_tag_id=1&view=table

**Comment by stephanosm** [comment]
Few small problems I noticed.
1. There should be a color on the sorted column title different from the unsorted ones
2. The Underline column titles do not appear on Google Chrome. They work well on IE and Firefox.
3. Also I tried to test it from my Mobile and I see another problem, that the results are not clearly visible. The font color is too light and difficult to read.

**Comment by Blandine-AA** [comment]
@joshi1983 , there seems to be too many problems on this issue. So, I suggest not to release it for Demo 0.0.2. Or, if we release it, can we draft a workaround for the release notes ? Any other suggestion?

Good catch @stephanosm. Going forward, I think we should ask all testing to be done BOTH on laptop/desktop AND mobile devices. At least cell phone, and tablet if possible!

**Comment by joshi1983** [comment]
@Blandine-AA just because someone has ideas for improvement doesn't mean it has "too many problems".  I disagree that it is unreleasable.  What Stephanos is bringing up aren't nasty bugs.  These are just minor improvements from his perspective.  I implemented what I agree are improvements and they are available on app.accesslocator.com but not demo.accesslocator.com because extra effort seems needed when updating demo since we've put release notes on the presentation site.

@stephanosm I didn't implement the colour difference unless you hover over the links because the underlining looked clear enough alone.  The underlining shows in Chrome for me.  Can you use CTRL+SHIFT+R to thoroughly reload on Chrome? 

Here's a screenshot from my Chrome browser:
![image](https://cloud.githubusercontent.com/assets/11838191/24082488/deb714d2-0c9c-11e7-89cd-dc0387d37c38.png)

**Comment by stephanosm** [comment]
Working fine on Chrome as well.

**Comment by Blandine-AA** [comment]
@joshi1983  regarding your comment
> just because someone has ideas for improvement doesn't mean it has "too many problems". I disagree that it is unreleasable. 

This point in my comment was just my perception. Also I asked for suggestions on how to handle this issue for Demo 0.0.2 as I said here:
> So, I suggest not to release it for Demo 0.0.2. Or, if we release it, can we draft a workaround for the release notes ? Any other suggestion?

What is your suggestion then? What is implemented that you agreed on as requirements to put in the release notes?

**Comment by joshi1983** [comment]
I'd suggest no change to release notes based on the suggested underlining of columns and colour changes from Stephanos.  

It is all very minor and covered under "Added map and table views for location search results" from the presentation site at [accesslocator.com/releasenotes](http://accesslocator.com/releasenotes).  

The only minor problem Stephanos was bringing up was that some users may have trouble noticing that the sorted column can be selected.  It doesn't stop anyone from seeing their lists of locations.  It won't stop anyone from accessing the essential functionality of the table/spreadsheet view.

**Comment by Blandine-AA** [comment]
Closing this issue based on @joshi1983 comment above

**Comment by joshi1983** [comment]
I added #265 so we can keep Stephanos' comment on his mobile device testing on our radar for later.
