### ISSUE TITLE
App name hardcoded?

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#165]
Is the app name "AccessLocator" defined as a general variable so that it is used everywhere?

When signin in with Google, the autorisation says: **-hhaccessibility would like...,** I don't know where the name **-hhaccessibility** comes from.

Can this fixed so that only the appname variable is called, for consistency?

**Comment by joshi1983** [comment]
The application name is hard coded in the application and information sites.  I think @brucelau-github will be quickest to get the application name(AccessLocator) updated for Google authentication.  Can you update that, @brucelau-github ?

I'm assigning Bruce because I think he can do this faster.

**Comment by brucelau-github** [comment]
Yeah.  I know how to troubleshoot this problem.

**Comment by brucelau-github** [comment]
This problem has been solved.
![screenshot from 2017-01-04 13-11-12](https://cloud.githubusercontent.com/assets/22227484/21654914/99ca5416-d285-11e6-9c5a-44faaba4d69a.png)

**Comment by Blandine-AA** [comment]
Thanks Bruce for the quick fix.

My main question was not to hardcode the application name everywhere not just in the Google authorization form. Has this been also fixed or just the Google authorization form?

**Comment by joshi1983** [comment]
What was changed is only with the Google's records.  The source code for the project wasn't modified.

Your question about it being hard coded sounds like it asks for an implementation detail that I'm not sure why you'd be concerned about.  The application name is in a central place in the project.  It is represented in the best way I think possible.  It is scattered throughout our github issues and comments so if it was to be renamed, it'll be updated in just a couple places in the project source code but potentially over 100 comments and issues on github.  I can't think of a way to do it better than that.  We definitely don't want the application name, something that will hardly ever change, put in the database because that will be more complex, difficult to maintain, and inefficient than keeping it where it is.

Are you worried that we'll update the name of the application frequently and have work slow down from people spending their time on it?  You won't have to worry about that.

**Comment by joshi1983** [comment]
I assigned this to Blandine to answer the questions on it or close the issue.

**Comment by Blandine-AA** [comment]
I'll close this since Josh seems to be ok with the design.
