### ISSUE TITLE
Home page : add slogan in quotes below AccessLocator in the blue box

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#177]
![image](https://cloud.githubusercontent.com/assets/20052162/21986886/4b4f3556-dbcf-11e6-8baa-1288bf8dc70c.png)

**Comment by joshi1983** [comment]
Do you want the "Find accessibility information on locations..." still there in another paragraph under the slogan?

Do you want the current paragraph removed?

Also in the same area, do you think the repetition of "AccessLocator" is good?  I'm leaning toward "yes" but it seems worth asking because "AccessLocator" is both in the top header and just above that paragraph.

**Comment by joshi1983** [comment]
I assigned to @Blandine-AA to more quickly get some questions answered before finishing this.

**Comment by Blandine-AA** [comment]
@joshi1983 

Yes we need to repeat the name and leave the current paragraphe.
Add the slogan in quotes just under the name, in Italic would be nice.
Then leave some space before the current paragraph and the slogan.

**Comment by joshi1983** [comment]
That answers everything, @Blandine-AA.  Thanks.  I'll probably get that done tonight.

**Comment by joshi1983** [comment]
@Blandine-AA check the work at [http://app.accesslocator.com](http://app.accesslocator.com).  If it looks good, please close this issue.

**Comment by Blandine-AA** [comment]
I think it looks nice!
