### ISSUE TITLE
Rating : make the rating feature work

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#200]
See #30  for mockups
We only implement the web app views. 
Other related issues: #108, #109

**Comment by joshi1983** [comment]
This is how I have it so far.  I didn't put the changes up yet because it doesn't work.

![image](https://cloud.githubusercontent.com/assets/11838191/23006238/a00dd9c8-f3ce-11e6-8a16-227cbd037fc7.png)

I based it roughly on:
![image](https://cloud.githubusercontent.com/assets/11838191/23006276/d60568f2-f3ce-11e6-9a20-b24871c3791c.png)

I was also trying to repeat some of the button styles used in the contact page, sign in, and sign up.

**Comment by areebakamal** [comment]
When the user is RATING: 
'Parking', 'Entrance', 'Public Areas', 'Bathrooms', 'Amenities' will look like the image you posted/ the one pasted below:

![7ratebuildingdecv3](https://cloud.githubusercontent.com/assets/23005093/23050054/fc630094-f48d-11e6-9957-f6386e25b9db.jpg)

The side panel should "float" as you scroll down so user doesn't have to keep scrolling up to change tabs for the longer categories. 

'Upload Images' will look like this:
![7ratebuildinguploadimages](https://cloud.githubusercontent.com/assets/23005093/23050125/6706903c-f48e-11e6-92b7-cd517c342eb8.jpg)


'Place Offering' will look like this:

![7ratebuildingplaceoffering](https://cloud.githubusercontent.com/assets/23005093/23050094/3511b50c-f48e-11e6-84d8-9d2a7d98cbbf.jpg)
![7ratebuildingplaceoffering2](https://cloud.githubusercontent.com/assets/23005093/23050095/3514e8a8-f48e-11e6-9b4d-8b77b282540a.jpg)

When the user is VIEWING the reviews, it will look like the following:

![7ratebuildingparkingviewww](https://cloud.githubusercontent.com/assets/23005093/23050196/c6f64578-f48e-11e6-98dc-5629f30869fa.jpg)

The 'View' page will be accessed by clicking from the following image:

![criteriapage about building](https://cloud.githubusercontent.com/assets/23005093/23050244/136c20da-f48f-11e6-8899-5a1f02d466e0.jpg)

**Comment by Blandine-AA** [comment]
- "Place Offering" should be renamed to "Location  Offerings"
- There is a new category that was added to the list: "Elevator"

Once we have the initial list of category and criteria validated, I will post it. 

In the design/implementation consider that at one point in time, we might need to add new categories.

**Comment by Blandine-AA** [comment]
@joshi1983 ,
- When hovering on the "Not Applicable" button, it should popup and info box that says "Location does not require this"
- We might need to add a 4th value for "I Did Not Look at This", even though it will not be used in the calculation. It might be used for other purposes. The feedback from the Accessibility person at the City of Windsor was positive about that column and the new list of criteria and categories.

**Comment by Blandine-AA** [comment]
My comment above needs to be reconsidered based on the discussion we had Friday Feb. 17th at CAW as a group.

It was discussed that we need to provide extra info and pictures when possible for all criteria. The extra information will be displayed eventually in a popup windows when clicking on the criteria. Design hasn't been finalized. Need to discuss with UX/UI team: @areebakamal, @RumanaHakeem, @stephanosm, @kimficara.

**Comment by stephanosm** [comment]
We need to find other way than "hovering" as this is not applicable in mobile devices

**Comment by joshi1983** [comment]
I'll focus on this for a couple days this week.

I may not get all of this done this week but here's a few points that I still need to do:
- [ ] Get the "Submit" to save the session's rating data to the database so the public can see them in the location report.
- [ ] Update rating cache values appropriately.  Test any code that should be refreshing the cache.
- [ ] Make "Submit" show in the last question category instead of "Next" and make the "Submit" button invoke the same saving functionality as the "Submit" button on the left side.
- [ ] Make "Next" button navigate to the next question category.  It does nothing for now.
- [ ] Begin a readonly mode for the rating feature that shows rating averages from all users.  This would have "Edit" links to the corresponding edit section.  This is where users can see the ratings for each individual question.

**Comment by joshi1983** [comment]
I linked the popup on an individual location's report to the new reporting/rating feature but there are still some things you probably want.  Things I'm aware of include:
- [ ] Make the rating count on the location report popup over the map correct.  It is always 0 for now.
- [ ] Show the percentages in a format more attractive and graphical than simple percentage text.  Exactly how to do this still seems to be up for discussion.  Mockups from Areeba illustrate how this could be put in graphs but it didn't seem like Blandine or others were agreeing much on it.  I think Meagan also thought it was redundant to have the numbers both in a graph and a text format.
- [ ] Make sure the percentages are rounded to be consistent with #316.  I didn't remember this until just now.
- [ ] List comments in the report.  Every question category can have 1 or more comments.  The most recent 10 at most should be shown.  This may be good to break out as a separate issue.

**Comment by Blandine-AA** [comment]
@joshi1983 , Great work for the Rating feature. It's good to have all the criteria showing. The Ratings Edit and View look great!

But there are few issues with the implementation. 
- You forgot to update the rating values (columns) from the final criteria list document and implemented as per the old mockups. The finalized checklist and rating values are available on the Wiki : https://github.com/hhaccessibility/hhaccessibility.github.io/wiki/Accessibility-Criteria-Check-List-Finalized-April-3rd,-2017
- Currently it is not intuitive that clicking on the Accessibility category will lead you to the Rating feature. The current implementation behavior doesn't seem like the one that was initially discussed. It has some interest but we will have to review it
- The other issue I see has to do with the flow. We'll get Areeba or another UX Design student to work on it. A UX design meeting will be required to square that one!
- I guess the current implementation screen reader friendly. Correct?

**Comment by joshi1983** [comment]
@Blandine-AA you mentioned a few things that need deeper discussion/review/design which probably can't be done for a few weeks since that's how long Areeba could be busy.  Is this the only change that doesn't need her help?
- Add a "Didn't look at this" button on the ratings area.

Also, what do you suggest as an extra way to navigate to the rating feature?  We want a close button on the popup.  Should we also have a "Rate" button on the popup?  Should there be a "Rate" button elsewhere on the location with map report?

**Comment by Blandine-AA** [comment]
@joshi1983 , yes. Those will be the 3 changes not impacted by UX flow design.

Using "Not Required" should be good enough.

As per the grey boxes on the criteria list, i agree with you that some are incorrect, as we didn't complete the discussion. I would suggest that for now, you implement those as it looks right to you as explained in your comment above and we will adjust when doing "user/live testing" 

There should be a rate button anywhere where the user can have the opportunity to rate. Some of the mockups show it. There shouldn't be a rate button on the popup, as the intent is to provide information, only then we can provide the rate option, as it is implemented now.

**Comment by joshi1983** [comment]
I added the button and some data but still have to disable the "Didn't Look" button tonight.  I should be able to fix the spelling errors mentioned in the password recovery issue tonight too.

**Comment by joshi1983** [comment]
The "Not Required" buttons are now working and look like this:
![image](https://user-images.githubusercontent.com/11838191/26893358-0f2f32ea-4b89-11e7-93e2-d35adc5f15b5.png)

**Comment by Blandine-AA** [comment]
Tracey and Anne will be happy to see this !

**Comment by Blandine-AA** [comment]
@joshi1983, I'll PASS the test, but we I will open a new issue to track the Rating UX flow.
