### ISSUE TITLE
Discovery Activity : Accessibility Criteria : Kim

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#229]
Find guidelines here : https://github.com/hhaccessibility/hhaccessibility.github.io/wiki/Disability-criteria-discovery-activity-description

Then submit your results here by Monday Feb. 27th for all to have access to it and review.

**Comment by kimficara** [comment]
Here are two different locations where I tested out the survey.  The first location was the CAW building on the University of Windsor campus and the second location was the Willistead Park.  

One of the issues that noticed when testing the survey out at the park is that a lot of the sections are N/A.  An example of this would be the Elevator section since the park does not have an elevator.  I think we should have a radio button at the top of each section that the user can click and it will automatically  change all of the sections boxes to N/A.  I could see a user getting frustrated if they had to select N/A for each individual criteria.  It's also very hard to estimate if a door is wider than 38 inches or not so maybe we could give the user ideas of what they could compare it to since most of them won't have tape measures handy!

[CAW Survey.docx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/818152/CAW.Survey.docx)

[Willistead Park Survey.docx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/818153/Willistead.Park.Survey.docx)

**Comment by Blandine-AA** [comment]
Re-opening the issue as closing it does not allow review team discussion.
