### ISSUE TITLE
User Profile : Add number of reviews in My Reviews button

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#235]
- [x] I was thinking for the **My Reviews** button that we should show the number of reviewed locations in brackets like: **"My Reviews (0)"**. 
- [x] When clicking on **My Reviews (2)** button, it should show the list of  locations that the user has reviewed with a link to those locations.

The user knows immediately how many locations s-he reviewed. Since multiple reviews can be made by the same user on the same location, the number of reviews isn't the same as number of reviewed locations. It may be more understandable to the end user to show number of reviewed locations.

**Comment by joshi1983** [comment]
This works with the session for now but I should get it working with the database too this week.  It may not be ready for testing until next week when the rating feature is more complete, though.

**Comment by joshi1983** [comment]
This is ready for testing.
The suggested procedure is to:
1. Rate a location.  Don't bother making the answers accurate.  Just give random ones.
1. Notice that the number goes up by 1.
1. Rate another location.
1. Notice that the number of reviews on the profile goes up again.
1. Rate a rated location again.  Notice that the number doesn't go up this time because it was already rated.  Do you agree with this behaviour?  It is something I thought would be less confusing for users but if you disagree, it may be good to discuss the reasons and come to a good agreement on.

**Comment by balraj18** [comment]
Working great! For me, it is a fair concept. I rated 3 locations and got the expected results.
![image](https://cloud.githubusercontent.com/assets/25542570/26744203/f1aa6494-47b2-11e7-8713-31b8e45e948b.png)

**Comment by joshi1983** [comment]
@balraj18 did you check the count on the Profile?  

![image](https://cloud.githubusercontent.com/assets/11838191/26745727/ffb07766-47b9-11e7-9ced-62a60ea2a57e.png)

The calculated percentages from your screenshot are more related to #200.

**Comment by stephanosm** [comment]
The counter works fine. I have few other concerns though.
First, I am not sure why Adie Knox shows the address next to the name
![image](https://cloud.githubusercontent.com/assets/22602396/26746137/01b0357c-47bc-11e7-9432-98b1ac35f2e3.png)

Also, how do I see my Reviewed Locations? Is there any link that it can bring me here or I can only see my reviews after I rate a location? How about the idea of after rating the user is redirected to his profile and the Reviewed Locations appear under the Reward Program?

**Comment by balraj18** [comment]
yes it went up to 2 and stayed the same when I rated the same location again.

**Comment by joshi1983** [comment]
@stephanosm that looks like 2 questions.

1. **Why show the address?**  The address is added when it is defined to distinguish locations that share the same name.  In your screenshot, it shows a few locations like the Casino Windsor which don't have an address yet.
1. **How do you see reviewed locations?**  What you circled is a link.  All those location names can be clicked and will bring you to the location.

**Comment by joshi1983** [comment]
I'm closing this because @balraj18 found that the number was calculated correctly.

@stephanosm is there some improvements you think would make sense for another issue or issues?  I could break the location name from address into multiple columns like a spreadsheet.  I could also sort by location name alphabetically.  Do these sound good?  If the links weren't obvious, should the links be underlined like from the location search table view?

**Comment by joshi1983** [comment]
@stephanosm I added a couple improvements that I was considering.  Now the reviewed location list looks like:
![image](https://cloud.githubusercontent.com/assets/11838191/26753791/37c6f9a4-483c-11e7-878d-475ea7277c17.png)

**Comment by stephanosm** [comment]
@joshi1983 It is much better now. Also, I haven't realised that the "My Reviews(4)" button is an actual button. I recommend to make the button look more like a button or just a link.
