### ISSUE TITLE
Demo 0.0.2 Testing: Sign in with Google broken

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#246]
Now says that feature is under development. Was working in demo 0.0.1

@joshi1983 , please assign to a student as you see fits and set it to Critical.

**Comment by joshi1983** [comment]
It was in demo 0.0.1 as it was part of [this January 19 commit](https://github.com/hhaccessibility/hhaccessibility.github.io/commit/af126d0fba848d91355bfb2964bc05d9c999c44a) but I'll remove the Under Development message since we've decided since then that the Google authentication is ready for testing.

I'll work on it Wednesday.

**Comment by joshi1983** [comment]
@brucelau-github do you know why this might be happening in demo.accesslocator.com?
![image](https://cloud.githubusercontent.com/assets/11838191/23687524/e1010e24-037c-11e7-82e7-955e3aab2bcd.png)

**Comment by brucelau-github** [comment]
It works now and it seems a wrong operation on managing google api. I generated a new key pair for google+ api, and renewed them on our accesslocator server.

**Comment by joshi1983** [comment]
I tested and it works on both demo.accesslocator.com and app.accesslocator.com. I'm closing.
