### ISSUE TITLE
Demo 0.0.2 Testing: change "Rating" to "Accessibility Rate (%)"

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#248]
If we need to show the full table view, the following needs to be updated. Personally I would prefer to wait until the Rating feature is completed, as it doesn't add any value.
- Change "Rating" to  "Accessibility Rate (%)"

![image](https://cloud.githubusercontent.com/assets/20052162/23667079/c2cd494c-032a-11e7-9d12-f4415a9ed965.png)

@joshi1983, if you still want to show this, please assign to a student as you see fits, and set it to Critical. If not move it to Release  0.0.3

**Comment by joshi1983** [comment]
In future, things like this can be reviewed weeks prior to a demo release.  app.accesslocator.com had "Rating" shown for roughly a month and nothing was said about it.  Reviewing app.accesslocator.com earlier or more frequently would improve communication about requirements earlier on and thereby reduce the number of these surprises upon the next release.  app.accesslocator.com exists mainly for this purpose.

I can probably change this Wednesday evening.

**Comment by joshi1983** [comment]
I was lucky to get enough time to do this tonight.  I added the ready-for-testing label since we've done that with other issues recently completed.

**Comment by Blandine-AA** [comment]
@joshi1983 , nothing was said about it as this wasn't a priority until you decide to release it on Monday for the 0.0.2 release. So, this is your call to make this feature available. 

I wouldn't have released it until the rating feature is completed.

**Comment by Blandine-AA** [comment]
The reason why there is a Product Owner is to approve anything that will be released and also validate the release before it is being released.

As a product owner, I didn't validate the release of the demo 0.0.2 load on March 6, as I didn't have the list of all the issues that were to be released and hadn't reviewed their status.  Unfortunately! That's the reason why the release has been postponed. 
Normally, we should revert the demo site back to 0.0.1 because not only 0.0.2 is broken, but it wasn't ready for release neither.

So, in the future, unless I approve the content and I am satisfied with the status of all the issues, nothing will be released for demo. As Product Owner, it is my responsibility to manage the release content and date, and I can delay the release as long as it is necessary.

In Scrum, at the end of the Sprint/Iteration, there is no obligation to release the features. It is up to the Product Owner to decide if the features will be released to the "customer" or not.

**Comment by joshi1983** [comment]
I didn't suggest "Accessibility Rating" as an insult but as an improvement to how this project would be judged by others coming to it.  I didn't intend it to be taken as a personal attack and I'm sorry for coming across like that.

I'd like to get to the bottom of some of this confusion in case it helps the future.  You wrote, "if you still want to show this, please assign to a student as you see fits, and set it to Critical." How should I read that as low priority when you say to "set it to Critical"?  Why should a student be given a "Critical" issue when it could take a week longer to complete as a result and delay testers from looking at it?  I decided to do it because that instruction was confusing to me and I wanted anything holding up demo 0.0.2 release to be done ASAP for more rapid feedback from people testing it.

Maybe it would help to have an in person meeting the night of or 1 day before the next release to demo where you clearly give a yes or no to app.accesslocator.com becoming the next demo.  Maybe a couple days where you can test app.accesslocator.com prior to the meeting to help you come to a decision prior to the meeting.

We should also stop talking about specific dates to release, deadlines, or even having "monthly" demos since that's a big part of why I deployed to demo both "by January 1" and the Monday after our March meeting.  Continuing to sense the urgency to fix demo so it is ready as soon as possible was why I jumped on this issue too.

**Comment by joshi1983** [comment]
I'm closing this because I don't think we internally need to test this.
