### ISSUE TITLE
Round1 Testing: need a back button

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#249]
When in the any view (Table or Map) of the search location, if I select a location, I get to the map with that specific location and its accessibility informations. A "Back" button is needed at this point for me to go back to the exact page I had before.

This is a feedback from the first round of  testing by JMCC

**Comment by joshi1983** [comment]
That should be simple enough to do.  By round 1, do you mean this was feedback from the beginning of February?

I might get to this Wednesday but it may take a couple more days because I'll be taking on a few other issues too.

**Comment by joshi1983** [comment]
I guess you'd want the location search to appear left of the location name in the top as if it were a hamburger menu.  If we're unable to get a previous location search URL such as when a user just goes direct to that location from an external website, we could leave the spot empty.

**Comment by joshi1983** [comment]
@Blandine-AA can you check the mockup to see if that's good?  This issue would likely be good for some of the students looking for an issue but it won't be good for them unless the requirements are clearer.

**Comment by joshi1983** [comment]
@sidhunavroop are you ok with taking this on?  The requirements aren't clear enough to begin implementing a new feature but maybe you can continue the conversation about requirements until it is clear enough how we want this to work that you can begin implementing it.

Normally, I'd wait until the requirements are clear enough to implement but gathering and analyzing requirements yourself may lead to a deeper understanding of why we want the feature.

**Comment by Blandine-AA** [comment]
@joshi1983, I agree with your 2 comments. I'll review your design proposal and get clarification from JMCC. They are the users. Remember, we are providing a tool to people with disabilities and this needs to be user friendly. Even if it means making some existing browsers functionality redundant, but more accessible.

**Comment by joshi1983** [comment]
@gillbalraj was unassigned because he's in Alberta and won't be working on AccessLocator for a few weeks likely.

**Comment by joshi1983** [comment]
The back button was added.

![image](https://user-images.githubusercontent.com/11838191/33236853-af75b32e-d22e-11e7-8b95-1e7d1198e695.png)

This can be tested by:
1. Go to http://app.accesslocator.com
1. Click a location category or type in a keyword to search for a location
1. Click to see the location's overview
1. Click the new search button left of the location's name to go back to the location search
1. Open a new browser(Firefox if you used Chrome for the previous steps) and go immediately to http://app.accesslocator.com/location-report/460  This should not show the search button because you're visiting the report without making a location search.

**Comment by Blandine-AA** [comment]
Will be reviewed by JMCC and tested by users. 
Closing this for now as this **new functionality** has been implemented.
