### ISSUE TITLE
Location Search: Add Search Radius selector to "table" view

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#260]
@areebakamal found it too restrictive that the profile was the only place to update the search radius while she tested #205.

The new input can go left aligned under the "Location Search Results for ..." heading.

This issue will involve the following steps:
- [x] Add a new form to app\resources\views\pages\location_search\spreadsheet.blade.php.  This new form should have an input element and a save button.
- [x] Add a setSearchRadius method to app\app\BaseUser.php that saves to the user table if the user is signed in or to the session's search_radius_km key if not signed in.  See methods like setAddress, setLongitude, and setLatitude for examples of how to switch between saving to the table or saving to the session.
- [x] Add an api for saving just the radius using your new setSearchRadius method in BaseUser.  This new api should be a new method in LocationSearchController.php.  You'll need to add a route for it in routes/web.php too.  Use the HTTP method POST for this instead of GET since it'll be saving a new value.
- [x] Add a new public/js/location_search_table.js file and define some ajax calls to your new api when the user hits 'Save'.  When a successful response comes back, the JavaScript should refresh the page to include all locations within the new radius.
- [x] Test the search radius selector after arriving on the location search screen from the home page's keyword search.  Submitting a new radius should keep the results using the keywords from the home page.
- [x] Test the search radius selector after arriving on the location search screen from the home page's location tag links.  Submitting a new radius should keep the results using the same location category.

**Comment by areebakamal** [comment]
![whatsapp image 2017-04-13 at 11 29 35 pm](https://cloud.githubusercontent.com/assets/23005093/25032391/c9289686-20a1-11e7-806a-3e8b63adce20.jpeg)
![whatsapp image 2017-04-13 at 11 29 36 pm](https://cloud.githubusercontent.com/assets/23005093/25032392/caa35e60-20a1-11e7-9e90-11e186fa5d1f.jpeg)

Search Page:
At the top we have radio buttons for advance and basic search. Basic search will reflect the home page search. 
Advance Search:
At the top you can select the buttons by clicking on which accessibility category matters to the user for this particular search. The first box with 'City, ON, Canada' doesn't necessarily have to be a city but by default it says Windsor as is on the homepage. 
Keyword includes the place name such as Leddy Library. 

When you tab into the category box or click on category then the category table such as Restaurant, Healthcare, etc expands and loos like the table on the homepage. You can click on the on the tile and that will be reflected in the 'categories' box. 


Location Search Results Page:

At the top there will be buttons that contain your search items. This will include your keywords such as 'Leddy' 'Library' 'Entrance' 'Elevator'. It has an 'x' on the corner in case you want to broaden your search or change. Example: For the previous search of Leddy Library with Entrance and Elevator, let's say  the accessibility percentage is too low, or the distance is too much or it's not showing any results. 

You could close 'Leddy' and now it will show any library that has an accessible entrance and elevator and the page will reload with the new results.

**Comment by areebakamal** [comment]
I guess there should also be Radius or Distance on the Search page and that will be reflected as a button on the search results page too. Will post high fidelity mockups later.

**Comment by areebakamal** [comment]
Also, I was testing with screen readers. I tested the profile page and search results page with two screen readers. NV Access and ChromeVox extension. With NVA, it reads if you move your mouse over it. In ChromeVox, there is an option for using the mouse cursor as focus for reading. But I didn't see that in NVA. 
Basically NVA works really well if you hover you mouse over text, it reads the text on the accordion menu used on the profile page as well. But the blind user will not know where cursor is at especially because we have our layout with many items. The way people use the mouse is if it they go down slowly in one order and the screen reader will read line by line. But if there is text and buttons laid out horizontally, it doesn't work work. The layout should be designed so that it has a more stacked view with one item per line so the screen reader can follow well. 

Basically, I think there should be two different layouts. A general layout like the one drawn above and a more screen reader friendly layout. I think we need to test thoroughly and see what works and what doesn't. Screen reader testing itself can be a large issue that many people can test both real users and testers on our team.

There is a lot of talk online about screenreader and javascript and how screen readers parse the DOM. I read a few articles but I think best way would be to actually test it. 

Here are some screenreaders:
'Install NVDA, a free screen reader for Windows.
If on a Mac, turn on VoiceOver.
If on Ubuntu / Gnome, install Orca
Download and run a trial of JAWS.
If on iOS, turn on VoiceOver.
If on Android, turn on TalkBack.
Try Narrator on Windows.'

Josh mentioned Jaws, GW-Micro Window-Eyes.

**Comment by areebakamal** [comment]
Ok commented on the wrong issue I had open.

**Comment by joshi1983** [comment]
@brucelau-github as per our gmail chat, read the issue description more carefully.  There is no need to create an API for downloading locations in this issue.

If you were thinking of some fancy single page application-like technique where JavaScript fills the page's location list, that would go against the reason we're not making a single page application.  The more JavaScript manipulation of the document, the worse the site is for screen readers.  Instead of that, you must "refresh the page" so the server regenerates all the HTML and screen readers will see the change.

**Comment by brucelau-github** [comment]
Okay. I just need to refresh the whole page other than part of the spreadsheet page. am I right?

**Comment by joshi1983** [comment]
Yes, reload the entire page.  Something like location.reload(); should work.

**Comment by joshi1983** [comment]
This is ready for testing on http://app.accesslocator.com

**Comment by intherightdirection** [comment]
When updating the search radius, the number input allows you to select numbers less than 0. Although no action is generated from a negative distance, it still shouldn't allow you to select less than 0.1

**Comment by brucelau-github** [comment]
how to react to this issue? pop up a message or giving some  error on page. @joshi1983 
any idea?

**Comment by intherightdirection** [comment]
I am assuming you are using <input=”number”>, use min=”0.1” in html

Sent from Mail for Windows 10

**Comment by joshi1983** [comment]
A little change from @brucelau-github was deployed.  

You can try again at:
http://app.accesslocator.com/location-search?location_tag_id=2

It looks like invalid inputs are marked with red and that seems fine to me.  What do you think of that Jared?
![image](https://cloud.githubusercontent.com/assets/11838191/26532148/520ccc2c-43c7-11e7-82f8-d132629e1dce.png)

**Comment by joshi1983** [comment]
I assigned to Jared since he started testing this.

**Comment by intherightdirection** [comment]
It is no different. The point is it requires an action or event to recognize bad input when you should be limiting the type of input anyways. The bad data is not going to go any further, I know but the point I was trying to make was you should not be allowed to even select a negative number. If you are fine with it, alright. The change was kind of unnecessary work because it didn’t really change anything.

Sent from Mail for Windows 10

**Comment by joshi1983** [comment]
If someone tried to type -2, what do you want to have happen differently?  Should it immediately be replaced with blank?

If someone hits the down arrow, you want the down arrow to stop lowering the value below 0.1.  Is that right?

**Comment by intherightdirection** [comment]
Correct.

Sent from Mail for Windows 10

**Comment by joshi1983** [comment]
This change was just implemented: If someone hits the down arrow, the down arrow will stop lowering the value below 0.1 and available at app.accesslocator.com.

If someone tried to type -2, what do you want to have happen differently? Should it immediately be replaced with blank?  Does this matter?

**Comment by intherightdirection** [comment]
Doesn’t matter. Someone is unlikely to type a -number, but it will not trigger any further action, if error checking checks for that, Bruce made it more obvious with the red.

Sent from Mail for Windows 10

**Comment by joshi1983** [comment]
Are you satisfied with the feature now?  Would you consider it passing or failing now?

**Comment by intherightdirection** [comment]
Pass.

Sent from Mail for Windows 10

**Comment by joshi1983** [comment]
I'm closing as this issue has passed testing.
