### ISSUE TITLE
User Profile : Profile not saved when launching My Reviewed location page

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#349]
While updating my profile, if I click on "My Reviewed Locations" button, It opens a new page. which is good, but then my changes in progress on the profile are not saved. when I click on Profile, the changes are gone !

To avoid this, if changes have been made to the profile and haven't been saved, the user should be reminded that he made changes to the profile and asked if he wants to save the changes before leaving the page, whether he is leaving the page by clicking on another menu tab or click on the "My Reviewed Locations" button.

**Comment by brucelau-github** [comment]
@joshi1983 Do you have any suggestion for this issue?

**Comment by joshi1983** [comment]
Maybe the solution for this could be a profile_save_prompt.js file that makes a few attempts to interrupt the user before leaving the profile without saving such as:
- Add a function to profile_save_button.js that can be reused in profile_save_prompt.js that to check if a change was made.  This would be similar to the $("#profileForm").serialize() === DefaultFormValue check you do to decide if the Save Profile button should be enabled.  This would be useful in profile_save_prompt.js because it would tell if a prompt is even necessary.  No unsaved changes means no need to prompt.
- Implement a function that shows a custom dialog confirming if the user wants to save before leaving.
- Look into window.beforeunload.  It looks like that might help you listen for the navigation events.  I found a reference to it at: https://stackoverflow.com/questions/1289234/alerts-when-navigating-away-from-a-web-page

One concern I'd have is that this may not work well with screen readers.  It'll be important to see how a screen reader like NV Access would behave when the confirmation dialog shows up.

**Comment by brucelau-github** [comment]
It seems we could not customize the popup message on windows before unolad event.

**Comment by joshi1983** [comment]
I merged @brucelau-github's work on this.  It looks good from what I can see.  It is using a standard browser feature to prompt the user when closing the browser, reloading, or navigating to another page.

**Comment by Blandine-AA** [comment]
@intherightdirection, could you please take over this testing? if yes, then assign it to you and remove Navroop. Thanks!

**Comment by intherightdirection** [comment]
We get a "Do not leave page trying" pop up to browse to another link and on browser or tab close. We also get a choice to not reload if we refresh page. This is only if information is not saved, otherwise it lets you go on your way. PASS
