### ISSUE TITLE
Presentation page: New Feature tab update for demo 0.0.4

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#363]
Update the "New Feature" tab on [AccessLocator.com](www.accesslocator.com) presentation page

 To be completed for Monday night, June 12
- [x] Deploy demo version 0.0.4 - @joshi1983
- [x]  Update release version - @joshi1983
- [ ]  Add release note to New Features page - @areebakamal / @joshi1983 

List of closed issues in [release 0.0.4](https://github.com/hhaccessibility/hhaccessibility.github.io/milestone/7)

**Comment by joshi1983** [comment]
@areebakamal let me know if you want to take on the presentation page changes.  Remember that you'll have to download the updated files as of the SVG logo and the release notes updates from a few weeks ago.

@Blandine-AA I plan to handle the demo release between Friday and Sunday night instead of doing this ASAP so a last few things such as #200 can be closer to ready for release.

**Comment by joshi1983** [comment]
Are these good release notes?  Demo 0.0.3 was April 27.  This is all the change I can think of since then.

- Made location rating feature work
- Made My Reviews button on profile work
- Made question category navigation from location report work
- Made password recovery work
- Replaced home page background image
- Prevented users from losing unsaved data on profile
- Clarified Select All / Unselect All on profile
- PNG Logo replaced with SVG

Not sure if we want to include these few items since some testing failed:
- Restricted countries in profile to USA and Canada
- Added province/state suggestions based on selected country

**Comment by Blandine-AA** [comment]
@joshi1983 Are they based on the release 0.0.4 issues list?

**Comment by joshi1983** [comment]
I based that on a memory refreshed by reviewing issues closed since April 27.  

I didn't strictly stick to a 1 point per issue.

**Comment by Blandine-AA** [comment]
The most important is to list the main and visible changes for the end user.. 
Here is the reviewed and updated list.
**The following functionality are added in this release:**
- Location Rating Feature 
- **My Reviews** button on the Profile page
- Password recovery - Allow users to recover their password if they forgot it!
- Updated home page background image
- Improved Profile saving behaviour
- Improved Select All / Unselect All behaviour on Profile
- Restricted countries in Profile to USA and Canada
- Added province/state suggestions based on selected country

The "Rating Feature coming soon flag" can be removed now since the rating feature is now implemented !

**Comment by Blandine-AA** [comment]
@areebakamal , above is the finalized release notes. Please go ahead and update the presentation web page.

**Comment by areebakamal** [comment]
I've updated the site with the release notes.

**Comment by Blandine-AA** [comment]
@areebakamal , while testing it I noticed that there is one feature missing that the use will notice clearly. Please add it.
- Enhanced view of category description to show at the bottom of the  page when hovering or tabulating on a specific category.

**Comment by areebakamal** [comment]
Added it.

**Comment by Blandine-AA** [comment]
@joshi1983 , @areebakamal , link to demo on RN for 0.0.3 will need to be removed at one point as for  0.0.2 title. Correct? or are we keeping the previous demo versions available from now on?

We had that discussion few time already @joshi1983, what do you suggest? 

My recommendation would be to keep the previous demo release available internally (for example create a **demo-0.0.3.accesslocator.com** stream) and only link the latest release title to the newest demo release.

**Comment by joshi1983** [comment]
@areebakamal told me she'll remove the link from 0.0.3 in a minute.

I have some branches for demo-0.0.2 and demo-0.0.3 that can be used to deploy those if we ever wanted to but maintaining those deployments wouldn't be beneficial enough to be worth the computing resources and complexity.  It would be barely worth any value while taking up as much memory as the demo and app deployments.  It would also be an extra knowledge to transfer to anyone else who would take over where I left off if/when that day comes.  It is nice to keep things as simple as possible when we have such limited resources in both money and people's time.

**Comment by Blandine-AA** [comment]
That's what I meant! I didn't say to keep them on the presentation web page. 

There is no need to keep more than 1 previous release, But if it is no work to keep them around, that's fine!

**Comment by joshi1983** [comment]
0.0.4 was deployed with the footer text saying 0.0.4 and the release date as Monday.  I checked those subtasks off because they are complete.

@areebakamal just a reminder to remove the link for 0.0.3.
![image](https://user-images.githubusercontent.com/11838191/27008231-51b43d3c-4e3a-11e7-92b6-cc80c5e3c9c0.png)

**Comment by Blandine-AA** [comment]
accesslocator.com release notes web page looks good to me. So, I will close this issue.
