### ISSUE TITLE
Rating Feature: Allow a user to add a location

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#386]
After the update meeting today with JMCC, it was mentioned to allow a user to enter a location that is not yet in AL.

To avoid duplicates and wrong/phony entries, I suggest to use the user GPS location to identify the location he wants to add. IF the location name can be retrieved based on GPS coordinates, then have the user validate it before adding it.

Also, having the GPS coordinates of the location will prevent duplicates, some thinking will have to be done here to define the proper algorithm/process.

**Comment by joshi1983** [comment]
The previous plan was to import everything and not let any user add a new location but letting people add their own locations sounds fine to me.  For ratings information, we planned how to drawn out inaccurate information and we'll need a plan for how to minimize bad information on user-created locations.  

The longitude and latitude is definitely needed but we'd need a UI for selecting it since the user might not be exactly where the new location is and they might be adding it using a device that has no GPS sensor such as a laptop.  The UI for specifying latitude and longitude could show a map of where a typed address is or let the user click on the map to point out where the location is.

Preventing duplicates could involve a few things.  Here are a few ideas:
- The new location gets staged for addition similar to our location ratings before they are submitted.  These new user-created locations could be available for them to rate but not available to the general public until they get reviewed by someone more internal to the project.
- Access to create new locations could be restricted to users who have rated enough locations well to earn our trust.
- We can store what user created each location so if a user or group of users is found to have added bad information, we can more easily isolate the ones they've added and remove them.

**Comment by Blandine-AA** [comment]
@josh, during the meeting @stephanosm mentioned a google tracking tool that can be useful to use. If he can add more details about it here that can be helpful to workout the design plan.

**Comment by joshi1983** [comment]
I added a field to the location table to store which user created the location because that seems useful regardless of anything we learn from further discussion on this.  I didn't mark this "working on it" because I did this little step quickly and I'm not actively working on it now.

The following work still needs to be done:
- Some more discussion of requirements.  A few specific questions include:
- After creating a new location, do we also want an interface to update information on that location?  
- Should users be able to delete locations they created?  I guess a user could accidentally create a location and want to undo the mistake but we also won't want this to destroy ratings information.
- A comment from @stephanosm is still needed on the  google tracking tool mentioned in an earlier comment from Blandine

**Comment by Blandine-AA** [comment]
@joshi1983, what user name do you have for AL loaded locations? I remember that for other apps imported data we thought about using something like "AccessNow_User". We should probably define/finalize the naming convention/format for that.

**Comment by joshi1983** [comment]
We have NULL as in no associated user for the current locations.  Every location has an associated data source but it is only the initial ratings that are made by dummy user accounts.

**Comment by joshi1983** [comment]
Here is a checklist of work that I see needed for this.  Some work may be broken into separate issues:
- [ ] API for creating new location: A method for creating a new location needs to be added and routed to from routes/web.php
- [ ] API for guessing which location tags/categories apply for a location's name.  This would be useful for defaulting them for the end user.  A lot of data on this is in importers/utils/data.  This would ultimately be called using AJAX requests and should respond with JSON.
- [ ] API for guessing which location group applies for a location's name.  Similar to the API for location tags, this would be useful for defaulting a value for the end user.  For example, a place named "McDonalds" should be in the location_group for McDonalds.  This would ultimately be called using AJAX requests and should respond with JSON.
- [ ] A page for listing all locations made by the current user
- [ ] A page for entering the required information such as location name, address, phone number... longitude, latitude, location group, location categories.  This page should make use of the API's for guessing appropriate location categories and the location group.
- [ ] Make location duplicate finder available to any user who is allowed to add a location.  Maybe this should be accessible through the list of locations they added.
- [ ] Add a location hard delete feature for locations added by the current user that haven't been rated by any other users.  This would let users delete locations they added by mistake.
- [ ] Add a feature for modifying existing locations created by the current user.  This may eventually apply to all locations but we can start it restricted to locations added by the current user.

**Comment by joshi1983** [comment]
I'm doing checklist items from the above checklist.

For the location add feature, I'll create the page initially based on the following notes:

The following information will be collected on the location add page:
- name
- address
- phone number
- longitude latitude selection (map)... repopulated as address changes or as user clicks on map
- location tag selection.. repopulated as location name changes or as user selects different values
- location group selection?.. if shown, repopulated as location name changes

A location add API willl be included in the same pull request.

**Comment by joshi1983** [comment]
This can be tested by:
1. Sign in at http://app.accesslocator.com.
1. Scroll to "My Reviews" and click "Locations".
1. Click the "+" in the upper-right corner of the locations list page.
1. Fill out information for a new location and created it.

**Comment by joshi1983** [comment]
Here are a few improvements mentioned from a Friday meeting with Blandine:
- [x] rename "Create New Location" to "Add New Location".
- [ ] rename "Create" to "Add" in the button
- [ ] add "None" option to the location groups/franchises.
- [ ] default to "None" when initially loading the screen or when a name is typed that doesn't match an existing location group.
- [ ] add "I don't know" to the location categories list.  This would be so it is clearer that the user doesn't need to select a category.
- [ ] reduce the white-space for the "Name" on a wide desktop screen.
- [ ] Make "Address" mandatory for all newly created locations.  For parks such as Jackson Park, Black Oak Park... they could still be given an address like "Windsor, Ontario".
- [ ] Add some title attributes to the location categories and location group.  Ask Blandine for the wording.

I accidentally removed the original list from #522 without making a new issue so the above list may be missing some information.  The above list is from my memory.

**Comment by joshi1983** [comment]
@Rubynguyen2910 see if you can do the last subtask item from a previous comment.  

To be clear it is:
"When a point is clicked on the map, auto-populate the "Address" with the location's address. This is the same behavior as on the "Home" page."

**Comment by Rubynguyen2910** [comment]
This is ready for testing.  The address should be filled in automatically when clicking on the Add Location map.
