### ISSUE TITLE
Create importer tool for McDonald's

### ISSUE THREAD

**Issue by yepterence** [hhaccessibility/hhaccessibility.github.io#394]
https://www.mcdonalds.com/ca/en-ca/restaurant-locator.html

**Comment by joshi1983** [comment]
How's the importer or the effort to get a big dump of data from McDonalds going, Terence?

**Comment by joshi1983** [comment]
I unassigned Terence because he hasn't been active with AccessLocator for a few months and I want to make this issue more available to new volunteers.  Terence talked of possibly contacting people from McDonalds to get the information without scraping the website but I didn't hear anymore about it.

**Comment by skwaitko** [comment]
Okay, will give it a go.

**Comment by joshi1983** [comment]
I'm attaching a couple files that Shawn emailed me.  They're the work that was done toward this import tools so far and ready for someone else to polish them up and make a pull request.
[mcdonalds.zip](https://github.com/hhaccessibility/hhaccessibility.github.io/files/2298940/mcdonalds.zip)

**Comment by joshi1983** [comment]
I pushed up a branch but it needs more development.  For now, it downloads no data from McDonalds.

**Comment by joshi1983** [comment]
I pushed up some more work on the new McDonalds import tool.  It is almost ready for pull request and merge but I have to fix some problems when importing the CSV into our seed data.  There is a lingering Unicode character encoding problem.

**Comment by joshi1983** [comment]
The McDonalds import tool was merged along with roughly 100 new McDonalds locations added to our seed data and to app.accesslocator.com's database.  This includes some imported ratings related to WIFI and parking questions that were converted from parking and WIFI information available at mcdonalds.com.

There isn't any functionality to test for this so instead of keeping this open for testing, I'm closing the issue.
