### ISSUE TITLE
Testing: Demo version info blocks the last line of the screen

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#401]
Testing on iPhone... When we make a search and there are lot of results then we can’t access the last result as it remains hidden beside the footer showing the version information.

This is not related to the app itself but to how the version info is added to the demo app.
![image](https://user-images.githubusercontent.com/20052162/32745479-e05d490a-c880-11e7-8ba6-e3664b408d80.png)

**Comment by joshi1983** [comment]
I'm planning to test carefully for this bug when releasing 0.0.5 but not fix it for the deployment of 0.0.4.  

Fixing this in demo 0.0.4 months after it was released would be effort better spent on 0.0.5 since the next release should happen soon and hardly anyone is looking at demo.accesslocator.com right now.  I'll circle back to this if I run out of more important issues.

**Comment by Blandine-AA** [comment]
No need to change 0.0.4
