### ISSUE TITLE
Testing: Location info missing in some cases

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#404]
While displaying a selected location some are missing the address or the address is incomplete. Why?
![image](https://user-images.githubusercontent.com/20052162/32799758-9cc69b26-c946-11e7-951b-645aee8a4477.png)
![image](https://user-images.githubusercontent.com/20052162/32799802-b52efdf2-c946-11e7-8cf2-9f16e9287847.png)
![image](https://user-images.githubusercontent.com/20052162/32845704-6da3210e-c9f3-11e7-8410-29f8e7028c1b.png)

**Comment by joshi1983** [comment]
The quick answer is that address isn't in all of our imported location data.  It is understood that we'd want to maximize the number of locations with addresses but there will be some rare exceptions like islands, monuments...  this doesn't explain "Basil Court" missing the address, though.  I think that may have been a location I added without adding its address.

I could make a spreadsheet with the locations that have no address information and review all our import tools to see if any of them aren't importing addresses even though their data sources provide them.

**Comment by Blandine-AA** [comment]
Can this work be done by a student? Is @yashankit17 available to work on this?
I also added a screen shot where the address is incomplete.

**Comment by joshi1983** [comment]
@Blandine-AA we have 8852 total locations of which 5849 have blank addresses.  That's too many locations to manually update.  If he can make a practice pull request like Prince has made, that would be a step toward taking on coding issues.  That could include him improving the import tools that collect more addresses.

@yashankit17 what are you up to now?  Are you ready to learn how to do a few things with git and make a pull request with it?

**Comment by yashankit17** [comment]
Sure josh
I’ll try to get to know about using the github now.
I have made the pull request already.

**Comment by joshi1983** [comment]
@yashankit17 I don't see your pull request.  This is where your pull request should appear:
![image](https://user-images.githubusercontent.com/11838191/32909180-e65ccb78-cad3-11e7-88d9-76a470fa24d0.png)

The pull request should be on the hhaccessibility project but I checked your fork in case it was mistakenly created there.  I don't see any extra branches or pull requests there either:
![image](https://user-images.githubusercontent.com/11838191/32909260-31192224-cad4-11e7-8442-78f4a19b91b7.png)

This article may help:
https://github.com/hhaccessibility/hhaccessibility.github.io/wiki/git-commands

Also, Prince made a pull request from his laptop a couple weeks ago.  He might be able to answer a few questions.

**Comment by joshi1983** [comment]
@yashankit17 made the practice pull requests so he's ready to take on some code changes.  He never used Python and the import tools would be a little unfamiliar to him so I thought I'd be better to take this issue on.  I assigned #397 to him instead because that would involve mostly JavaScript which he's much stronger with and expose him to the web application.  Increasing his familiarity with the web application should prepare him for other web application-related issues and #404 was basically created from Yashankit and Prince's feedback.

**Comment by joshi1983** [comment]
I plan to do the following work toward this issue:
- [ ] Merge extra location details into existing locations upon releases.  This will include writing a new tool that compares the current database with seed data.  This tool will at minimum add addresses and phone numbers if they are blank.
- [ ] Update the CSV to JSON conversion tool to merge data such as address and phone number into matched existing location data.
- [ ] Test the JSON to mysql merge tool by recreating the database with a dump of demo.accesslocator.com's database and running the merge tool.  Verifying that the new addresses get set on the intended locations
- [ ] Test that the CSV to JSON conversion tool changes by making a CSV with a couple locations with newly added addresses and phone numbers and checking the JSON files for desired changes

**Comment by joshi1983** [comment]
The address for Basil court and roughly 20 other locations were manually updated to test that the merge tool I made works and reduce this issue's problem just a bit.

These new addresses were added to app.accesslocator.com's database without deleting any data.
http://app.accesslocator.com/location-report/447

**Comment by joshi1983** [comment]
A bunch more address, phone number, and external web address information was merged into locations in Windsor.  This data is deployed at http://app.accesslocator.com.

I plan to still adjust scripts to:
- [ ] Add new locations that are in location.json but not in the database.
- [ ] Delete locations that are in the database but not in location.json and assuming that no user_answers are associated with them to prevent loss of user data

**Comment by joshi1983** [comment]
I plan to finish a duplicate finder feature for internal users and use it to look for duplicated locations that may have been introduced lately by the Google Places data import and the uwindsor campus map data import.

**Comment by joshi1983** [comment]
I removed the Working on it label because I'm not very active on this issue right now.  I have a duplicate finder branch that isn't merged and I have more work to do before it is ready.  I switched to working on the add location feature for now since it seemed more important to the demo 0.0.5 release and plan to finish that before returning to this and finishing the duplicate finder feature.

**Comment by joshi1983** [comment]
@skwaitko can you send me a spreadsheet with missing addresses, phone numbers, website URL's for locations in the Windsor area?

Also, a separate listing of locations that you suspect are duplicated would help.  These would be locations with similar names that are very close to each other.

These things can't be fixed by you directly because there is no feature in the site to let you add the information yet.  For now, I can handle the documents you give me and bring the improvements up to http://app.accesslocator.com.

**Comment by joshi1983** [comment]
@skwaitko how are things going?  I haven't heard from you in a couple weeks.  Let me know if you're getting busy with other things.  Everyone's availability has its ups and downs and it looked like you really poured yourself into AccessLocator for a week or so.

**Comment by joshi1983** [comment]
I unassigned @skwaitko because we didn't hear from him in a few months.

**Comment by joshi1983** [comment]
This issue is as complete as it ever will be so I'm closing.  A lot more address and phone number information was added.  We also have a new suggestion feature which should help us add similar information when it isn't yet there.
