### ISSUE TITLE
Not Rated Yet: to avoid 0% Accessible message

### ISSUE THREAD

**Issue by stephanosm** [hhaccessibility/hhaccessibility.github.io#486]
Currently, if a place is not rated it is shown as not accessible (see below). We need a button/image that says: Not Rated Yet! Be the first to rate this

![image](https://user-images.githubusercontent.com/22602396/35536357-9eb65a48-0514-11e8-8dc4-de7cf81f8045.png)

**Comment by Blandine-AA** [comment]
@joshi1983 , since we are updating this info block for 0.0.5, I suggest to make this change as well, that adds the "Not Rated Yet! Be the first to rate this location!" button across the box. Maybe we even disable the criteria categories buttons. 
When the "Not Rated..." button/tag is clicked by a signed user, the rating window should open and the "Not Rated...." button/tag will not show anymore.

**Comment by joshi1983** [comment]
If just 1 question is answered by one user, should the location be excluded from this case?

**Comment by joshi1983** [comment]
How does this mockup look to you?

![image](https://user-images.githubusercontent.com/11838191/35767017-a733fa7c-08b1-11e8-8d48-9dc06e374599.png)

Would that be better than what we already have or do you have ideas for something better that covers this requirement?

**Comment by stephanosm** [comment]
If we need to have something there urgently so as to avoid the issue of not rated locations, anything will do. However, this is very important issue since we want to attract users to rate locations. In terms of design this should be more fancy e.g. orange color with blue button, maybe? better design? I am not a designer myself but we need someone who has good design skills to come up with some suggestions. 
Also, this should be tight with the rating (points) system. e.g. "Be the first to rate this location and earn 100 points" . Remember we talked about having different levels of users who rate so to encourage rating? But again, this can come at a later time because it requires some thought and development time.

**Comment by joshi1983** [comment]
I brightened up the colours based on some discussion with Blandine but also added this for the case when 0 answers were submitted for the location.

This is how it looks on app.accesslocator.com:
![image](https://user-images.githubusercontent.com/11838191/36063277-b00f1db0-0e48-11e8-8b0a-0c845f800f1d.png)

**Comment by Blandine-AA** [comment]
@joshi1983 , it looks much better, and the toggle works perfectly 👍 

I think we should add a link to "Be the first to rate this location", that goes to the Rating page.

**Comment by joshi1983** [comment]
Yeah, "Be the first to rate this location" is a link to the rating page for the Amenities category.

**Comment by stephanosm** [comment]
@joshi1983  is there any bug with the new Not Rated Yet label? I checked some already rated sites (see below) and they still have the same label.

![image](https://user-images.githubusercontent.com/22602396/36064505-d302aa38-0e59-11e8-9233-d9a83833bf92.png)


![image](https://user-images.githubusercontent.com/22602396/36064508-e1c9097c-0e59-11e8-8f61-cec9049c7165.png)

**Comment by joshi1983** [comment]
@stephanosm yeah that's a bug.  I'll look into it and fix it.

**Comment by joshi1983** [comment]
I added underlining under the link based on today's meeting with Blandine.  We wanted to make the link more easy to recognize as a link.

I cleared the universal_rating cache which went stale somehow.  That fixed the problem for Basil Court and likely other locations temporarily.  I'm still in the process of adding tests to investigate how the cache got stale without clearing itself, though.

**Comment by Blandine-AA** [comment]
@joshi1983 , for consistecy, if we use the same color/background you have here for the Not Rated Yet info window, for the accessibilityinfo window, I think it will blend better on the map, instead of having the big blue "block". The buttons will have to really look like buttons instead of just table cells as it is currently. What do you think?

**Comment by joshi1983** [comment]
@Blandine-AA the colours are pretty similar between the "Not Rated Yet" state and rated.  Both have a nearly white background an nearly black text.

Here's a rated popup:
![image](https://user-images.githubusercontent.com/11838191/36345675-868cc0ea-13fd-11e8-9951-f7939c820ca5.png)

**Comment by joshi1983** [comment]
I could find the erroneous universal rating value that @stephanosm discovered in a January 31 backup.  I think the problem came from when I deployed some changes to app.accesslocator.com by manually updating an SQL dump.  I'm not absolutely sure but couldn't find any other cause after a thorough search.

**Comment by Blandine-AA** [comment]
Testing: PASS
