### ISSUE TITLE
Google API Keys unrestricted to be restricted

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#564]
There are unrestricted keys, created Nov 29 2017, on the project. Google asks to secure them.... know that I have MY credit card information in there. We don't want some people to use the key and ME being billed for it!
![image](https://user-images.githubusercontent.com/20052162/41262746-af8003ec-6db0-11e8-80a3-dc123d40695c.png)

**Comment by joshi1983** [comment]
On June 12 evening, all API keys were quite urgently restricted to minimize risk of exceeding any quota that could affect the account and production sites.  This included not including our development environments in places that can use the quota since localhost seemed like it could be too easily overused considering someone could be billed if the usage exceeds the quota or it could take down one of our production sites.

On June 12, I also emailed all active developers advising them to create their own Google Maps API Keys if needed for their work.  I can help them if needed.  This will probably impede the other developers a bit but there doesn't seem to be a way avoid it.


I'm not sure if Google is actually enforcing that billing enabled requirement yet.  I expected this to make big news where people who ignored the notifications would complain about their maps not working.

Even though this isn't a functionality issue, I'm relabeling "Ready for testing" in case you want to review, Blandine.

**Comment by singlaneha2205** [comment]
@Blandine-AA Please, provide the instructions for testing it. As I am not able to access the domain.

**Comment by singlaneha2205** [comment]
@Blandine-AA Please, provide an update on the same.

**Comment by M4ttoF** [comment]
@singlaneha2205 
```Even though this isn't a functionality issue that can be tested, I'm relabeling "Ready for testing" in case you want to review, Blandine.```

There isnt anything to test, so I think you were wrongly assigned to it

**Comment by joshi1983** [comment]
This is complete.  It isn't functionality any other volunteers needed to test.  After my June 15 comment, this became mainly something for Blandine to see for herself if she wanted to.  The information is now linked to my account so I'm closing the issue.
