### ISSUE TITLE
June focus group testing: Read out loud feature (screen-reader)

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#570]
As a user with reading problems, I would like the AccessLocator app to read out loud. 
I mentioned to the above user that the app was screen-reader compatible. 
- [ ] See if we should have an info box popping up on the home  page saying that the app is compatible with screen readers and the user can set that option in the profile. This leads to my next question
- [ ] Do we need the screen reader set in the profile or should this be automatic if the user has a screen reader app installed?

**Comment by joshi1983** [comment]
It looks like the underlying problem here is confusion over the "uses screen reader" checkbox.

The screen reader checkbox state is used to determine whether the question explanation feature is to pop up or navigate to another page.  Navigating to another page is easier for screen readers to work with.

Is this feedback coming from people who actually use screen readers?  Screen readers can be heavily customized far beyond anything feasible for us to recreate.  We could invest effort to provide alternative audio for specific places if needed.  Having a real human voice recording might be clearer if we know exactly what text we want read out.  

I discussed this with Jeff Szus from Hackforge just now and it sunded like he worked on a project where he could safely assume the Jaws screen reader was not used but set up automatically generated audio files on a server and played them when the user wanted.  Jeff said that Jaws would have a tendency of talking while audio clips were playing which made the experience of Jaws users worse.  We don't know if Jaws would be a popular screen reader.

**Comment by joshi1983** [comment]
I'm closing this for reasons mentioned in my previous comment and because of the months of no further justification to it.
