### ISSUE TITLE
June focus group testing: Big characters feature

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#571]
As a user with reading problems, I would like to make the characters bigger.
I mentioned to the above user that all cell phone know have accessibility settings to allow to make the characters bigger. This is part of setting up their phone or table for their usage. Nevertheless, for people using it on their computer/laptop, this feature might be needed.
- [ ] Have an AA button? 
![aa](https://user-images.githubusercontent.com/20052162/41351468-6f1555fc-6ee4-11e8-8066-23a46c75f2aa.png)

**Comment by joshi1983** [comment]
Did that user really have reading problems or was the user just imagining how other people with reading problems might use the website?

In addition to the accessibility settings built into most phones, there are some useful features in web browsers.  On a touch screen like most mobile phones, you can use 2 fingers to zoom in and out.

On a desktop, you can change the zoom level to be as big as you want.

In the following screenshot, I zoomed the site to 400% using Chrome:
![image](https://user-images.githubusercontent.com/11838191/41380543-495386fa-6f33-11e8-940e-1e2124bbe779.png)

There are a few ways to zoom on a desktop:
- Touching like with a phone if the screen has touch support.
- CTRL + Mouse Wheel adjustment
- Settings -> Zoom + or -
- Zoom in with: CTRL + '+'
- Zoom out with: CTRL + '-'

If this person really had a reading problem, it seems like either directing them to a video or educational material on how to zoom or providing some of that material directly in AccessLocator would be the best way to address their needs.  If they struggle to use the web browser's zoom feature, they'll struggle to use our reinvention of the zoom feature anyway.

**Comment by Blandine-AA** [comment]
User has reading problems and she wears glasses to read. She needs big characters, and that's HER feedback on the app testing. 

She also has physical problems and cannot use her fingers as easily as you may think and suggest. Just clicking on a button might be useful. That's also HER feedback on the testing. 

Something to think about !

**Comment by joshi1983** [comment]
If we add such a button and support this special big text mode, we won't be able to maintain it and test it to the same level as the regular mode because most users will be using the browser's zoom feature when needed.  We can make something that is really basic and looks ugly but makes the text big like she's requesting, though.

If we add such a button, users who know how to use the browser's zoom feature might think the button is the preferred way to zoom, though.

Where would such a button go?  What part of the app was she struggling to read?

**Comment by joshi1983** [comment]
In the meeting, it came up that the person asking for this feature didn't use her phone to access Android apps or websites.  She only used it for phone calls which is why she wasn't aware of more conventional ways to increase the size of text on her device.

This feature would be quite costly to maintain because text could wrap and look bad all over the place and every feature would be tested with both font size modes to verify that things don't look bad.  This doesn't seem worth doing until we have a few people who are more likely to actually use AccessLocator asking for this feature.  I suspect people who may actually use AccessLocator will use apps or websites on their phone often enough that the need for large font settings would lead them to discover Android's accessibility settings in their phones which would make this feature redundant.

**Comment by joshi1983** [comment]
Since this feedback came from someone who doesn't use a smart phone for web browsing or for applications on it, this issue seems low priority.  The user wasn't from our target audience or (s)he'd know how to use the phone's zoom features.  If people actually from our target audience make similar complaints, we can reopen this issue but I doubt that'll happen.

For these reasons, I'm closing this issue.
