### ISSUE TITLE
AL development environment not accessible anymore

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#593]
When I type app.accesslocator.com I get to accesslocator.com website. Any idea what happened? 
@joshi1983 Please assign someone to investigate.

**Comment by Blandine-AA** [comment]
This is related to #576 . I talked to @passionInfinite and tested it. It is working now.

**Comment by joshi1983** [comment]
I'm still experiencing this problem:
![image](https://user-images.githubusercontent.com/11838191/41986912-a3a58ee6-7a05-11e8-9724-5aceb07b2e95.png)

I tried with an Incognito Chrome browser and still experienced the problem just now.

Was the vhosts file updated as part of the HTTPS issue recently, @passionInfinite ?

I'm reopening just because I still see the issue after the issue was closed.

**Comment by passionInfinite** [comment]
@joshi1983 Lets discuss this on Hangouts.

**Comment by passionInfinite** [comment]
@joshi1983 fixed.

**Comment by joshi1983** [comment]
As of now, all 3 of our most important sites look as they should:
- demo.accesslocator.com
- app.accesslocator.com
- accesslocator.com

There's another issue where app.accesslocator.com doesn't have working third party authentication in both gmail and facebook but that's another issue @passionInfinite is working on.  Regarding that other issue, third party authentication still works for demo.accesslocator.com as I tested just now.

I'm closing this issue since it looks complete.

**Comment by joshi1983** [comment]
I reopened because http://demo.accesslocator.com is showing the same content as app.accesslocator.com now so part of this problem returned.

![image](https://user-images.githubusercontent.com/11838191/42322738-868c3f90-802b-11e8-9266-c9a13d69cead.png)

**Comment by passionInfinite** [comment]
@joshi I would suggest you to figure this out. Because it is now pointing to demo directory.

**Comment by joshi1983** [comment]
ok.  I'll figure out why this isn't showing the correct content.

**Comment by joshi1983** [comment]
It is fixed now and I retested the 3 main subdomains again:
- demo.accesslocator.com
- app.accesslocator.com
- accesslocator.com

It was fixed by adjusting one line in sites-available/laravel.conf.  There was a virtual host configured at the bottom of the file like:
```
<VirtualHost *:80>
    ServerName demo.accesslocator.com
    ServerAlias demo.accesslocator.com
    ServerAdmin accesslocator@gmail.com
    DocumentRoot /var/www/html/demo/hhaccessibility.github.io/app/public

    <Directory /var/www/html/demo/hhaccessibility.github.io/app>
        AllowOverride All
        Options All
    </Directory>
```
I just changed the top line to: ```<VirtualHost demo.accesslocator.com:80>```

The problem was specific to http.  https://demo.accesslocator.com was correctly pointing at the demo directory but not http://demo.accesslocator.com.

I'm closing because all 3 subdomains are working the way we want again.
