### ISSUE TITLE
June focus group testing: Add location feature difficult to find

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#611]
User wanted to add anew location, but we couldn't find the add location feature. We have to make it more visible an easy to find.

**Comment by M4ttoF** [comment]
We could try adding it to the header?
I could work on that if thats a position you are okay with

**Comment by joshi1983** [comment]
What was the user doing and what page were they on when they discovered that they wanted to add a location?  Did they search for the location and not find it?  Maybe it should be visible in the location search results pages for map and table views.

A new location shouldn't be added if it already exists.  It would be nice to make the link more visible when they discover that their new location doesn't already exist in AccessLocator.

**Comment by M4ttoF** [comment]
Can be tested by searching up a keyword that has no search results signed in, and not signed in

**Comment by singlaneha2205** [comment]
@M4ttoF, @joshi1983 and @Blandine-AA I tested the above scenario. When I am signed in it is working as expected. If the location related to my keyword doesn't exist I am displayed with the button of Add new location and I was able to add a dummy location successfully.
But when the user is not signed in, the user is displayed with two options: To add location either sign in or sign up. When the user clicks the sign in, the user is navigated to the user profile page. In my point of view, the issue here is the flow is broken as the user is navigated to user profile page, instead he should be navigated to add location page as he searched for the location which was not found before signing in. In the current scenario, the user needs to again search the location by the keyword he used before and then he will be able to add the location. This suggestion can be discussed by the team to check the feasibility and effectiveness. Otherwise, the flow is working fine once the user signs in and search the location.

**Comment by joshi1983** [comment]
@singlaneha2205 nice suggestion.

@M4ttoF can you make a new pull request that just updates your links to /signin to be to /signin?after_signin_redirect=/add-location.  

The signup form doesn't have support for after_signin_redirect yet so you will have to add that support to the controller.

**Comment by M4ttoF** [comment]
Changes have been merged so I am going to reassign @singlaneha2205 and change tag

**Comment by joshi1983** [comment]
The changes were deployed to https://app.accesslocator.com for testing but the "Sign Up" button was not affected.

Another issue #634 was created to document the remaining work that @singlaneha2205 wanted for the Sign Up workflow to navigate back to the add location feature eventually.

**Comment by singlaneha2205** [comment]
@joshi1983 @M4ttoF and @Blandine-AA I have tested the flow and it is working as expected. When the user is not signed in and search for a location using keyword and then select the sign in option to add the location which was not found. He was navigated to add location page and after that was able to add the dummy location successfully.

Since we have another issue #634  opened for signup flow regarding the add location. And the sign in flow is working as expected we can go ahead and close this issue.

**Comment by M4ttoF** [comment]
Closing as issue was tested successfully
