### ISSUE TITLE
Adjust home page layout to always show all 12 categories on laptops/desktops

### ISSUE THREAD

**Issue by joshi1983** [hhaccessibility/hhaccessibility.github.io#705]
On mobile devices, scrolling is acceptable but there should be enough space to show all 12 buttons on a laptop or desktop.

Here is how the home page typically looks on a laptop:
![image](https://user-images.githubusercontent.com/11838191/47996244-df0ab480-e0c5-11e8-8691-51f203f863b1.png)

This could be accomplished by reducing height of a few things when the viewport is wider than 960 or so pixels and when the height is less than 960 or so.  The solution should take into account whether the Sign in, Sign out buttons are showing since those would change the available vertical space quite a lot.

**Comment by stephanosm** [comment]
Correct. I think though we should have this issue as part of the whole User Interface ease-of-use exercise. This way we may consider alternatives (other changes) as well. We need to investigate the flow, from the moment a register (and unregistered) user comes to site. In addition, we need to investigate whether we need all the elements shown on the screen and with the same order, e.g. Sign in/Sign Out, map, having 4 categories in each row instead of 3, etc.

It would be nice to have a meeting to discuss this.

**Comment by joshi1983** [comment]
I shrunk the heights to fit with just 3 columns of location categories for now.  That looks better than it did so it seemed worth doing.  That's on https://app.accesslocator.com/ for you to look at.

Sure, we can widen the location categories area a bit to make room for 4 columns when the site is viewed on high resolution.  Want me to take a stab at that before next meeting?

**Comment by joshi1983** [comment]
I'll close this since the original description of the issue is covered.  We can make a new issue if the 4 columns seems important after our next meeting.
